const NAMES=['Aina','Hafiz','Mei Ling','Kavin','Sara','Daniel','Nadia','Arun'];
const LEVELS=[['foundation','Foundation',1,15],['developing','Developing',16,30],['standard','Standard',31,70],['exam','Exam',71,100],['extra','Extra Practice',101,160],['challenge','Challenge',161,200]];
const intros=[n=>`${n}'s class recently worked on a school activity. The task gave students a chance to practise English while completing a practical project.`,n=>`This term, ${n}'s class took part in a school project. Students worked in small groups and shared responsibility for different parts of the activity.`,n=>`The school recently organised an English activity, and ${n}'s class joined it. The students prepared their work over several lessons.`];
const mids=['During the preparation, the group checked its progress and made a few changes.','As the activity developed, students compared their ideas and improved the final version.','The class used the next few lessons to complete the preparation and check important details.'];
const outros=['At the end, the class discussed what had gone well and what could be improved next time.','After the session, the students reviewed the activity and shared what they had learned.','When the activity ended, the group packed the materials and talked about the experience.'];
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function sentence(pid,num,name,setNo,pos){const p=PAIRS[pid],arr=p[5],t=arr[(setNo+pos)%arr.length];return t.replaceAll('{NAME}',name).replace('{M}',`<span class="error">(${num}) ${esc(p[0])}</span>`)}
function passage(set){const [n,title,ids]=set,name=NAMES[(n-1)%NAMES.length],start=n>=71?9:1,s=ids.map((pid,i)=>sentence(pid,start+i,name,n,i));return `<div class="passage"><p>${intros[n%3](name)} ${s.slice(0,3).join(' ')}</p><p>${mids[n%3]} ${s.slice(3,6).join(' ')}</p><p>${s.slice(6).join(' ')} ${outros[n%3]}</p></div>`}
function row(setNo,pid,i,start){const id=`s${setNo}a${i}`;return `<div class="answerRow"><label for="${id}">${start+i}.</label><input id="${id}" class="ans" data-pid="${pid}" autocomplete="off" spellcheck="false"></div>`}
function card(set){const [n,title,ids]=set,start=n>=71?9:1;return `<div class="practiceTop"><button class="backBtn" type="button">← Learning Path</button><span class="setCounter">Set ${n} / 200</span></div><article class="set" data-set="${n}"><div class="setHead"><h3>Set ${n} · ${esc(title)}</h3><small>8 marks</small></div><p class="instruction">${n>=71?'Questions 9–16. ':''}Read the text below and correct the eight underlined errors. Write the correct word or words in the spaces provided.</p>${passage(set)}<div class="answerGrid">${ids.map((p,i)=>row(n,p,i,start)).join('')}</div><div class="actions"><button class="btn mark">批改</button><button class="btn alt reset">重新作答</button></div><div class="result" aria-live="polite"></div><div class="corrections"></div></article>`}
function setButton(set){const [n,title]=set,done=localStorage.getItem('done-'+n)==='1',saved=JSON.parse(localStorage.getItem('answers-'+n)||'[]').some(Boolean);return `<button type="button" class="setTile ${done?'done':''}" data-open-set="${n}"><span class="setNo">Set ${String(n).padStart(2,'0')}</span><span class="setTitle">${esc(title)}</span><span class="setStatus">${done?'✓ Completed':saved?'Continue →':'Start →'}</span></button>`}
function renderMenu(){const root=document.getElementById('practice');root.innerHTML=LEVELS.map(([id,label,a,b])=>{const ss=SETS.filter(s=>s[0]>=a&&s[0]<=b),done=ss.filter(s=>localStorage.getItem('done-'+s[0])==='1').length;return `<section class="level setMenuSection" id="${id}"><div class="levelTitle"><div><span class="pill">${done} / ${ss.length} COMPLETE</span><h2>${label}</h2></div><small>Sets ${a}–${b}</small></div><div class="setGrid">${ss.map(setButton).join('')}</div></section>`}).join('');updateProgress()}
function openSet(n){const set=SETS.find(s=>s[0]===Number(n));if(!set)return;document.getElementById('practice').innerHTML=`<section class="level singlePractice">${card(set)}</section>`;restore();updateProgress();window.scrollTo({top:document.querySelector('.layout').offsetTop-70,behavior:'smooth'})}
function norm(s){return s.trim().toLowerCase().replace(/[.,!?;:]+$/,'').replace(/\s+/g,' ')}
function mark(article){const ins=[...article.querySelectorAll('.ans')],blank=ins.find(x=>!x.value.trim()),result=article.querySelector('.result'),corr=article.querySelector('.corrections');if(blank){result.textContent='请先完成8题再批改。';corr.classList.remove('show');corr.innerHTML='';blank.focus();return}let score=0,wrong=[];ins.forEach((inp,i)=>{const p=PAIRS[+inp.dataset.pid],ok=norm(inp.value)===norm(p[1]);inp.classList.toggle('correct',ok);inp.classList.toggle('wrong',!ok);if(ok)score++;else wrong.push([i,p,inp.value])});result.innerHTML=score===8?'<span class="perfect">8/8 · 全部正确。这一套不需要订正。</span>':`${score}/8 · 请完成下面的订正。`;corr.innerHTML=wrong.map(([i,p,v])=>`<div class="corr"><b>${i+1}. 你的答案：</b> ${esc(v)}<br><b>正确答案：</b> ${esc(p[1])}<br><b>为什么错：</b> ${esc(p[2])}<div class="cn"><b>订正规则：</b> ${esc(p[3])}<br><b>例子：</b> ${esc(p[4])}</div></div>`).join('');corr.classList.toggle('show',wrong.length>0);save(article);if(score===8)localStorage.setItem('done-'+article.dataset.set,'1');else localStorage.removeItem('done-'+article.dataset.set);updateProgress()}
function reset(article){article.querySelectorAll('.ans').forEach(i=>{i.value='';i.classList.remove('correct','wrong')});article.querySelector('.result').textContent='';const c=article.querySelector('.corrections');c.innerHTML='';c.classList.remove('show');localStorage.removeItem('answers-'+article.dataset.set);localStorage.removeItem('done-'+article.dataset.set);updateProgress();article.querySelector('.ans').focus()}
function save(article){localStorage.setItem('answers-'+article.dataset.set,JSON.stringify([...article.querySelectorAll('.ans')].map(i=>i.value)))}
function restore(){document.querySelectorAll('.set').forEach(a=>{try{const v=JSON.parse(localStorage.getItem('answers-'+a.dataset.set)||'[]');a.querySelectorAll('.ans').forEach((i,k)=>i.value=v[k]||'')}catch(e){}})}
function nextSet(){const active=SETS.find(s=>{try{return JSON.parse(localStorage.getItem('answers-'+s[0])||'[]').some(Boolean)&&localStorage.getItem('done-'+s[0])!=='1'}catch(e){return false}});if(active)return active[0];const first=SETS.find(s=>localStorage.getItem('done-'+s[0])!=='1');return first?first[0]:200}
function updateProgress(){const done=SETS.filter(s=>localStorage.getItem('done-'+s[0])==='1').length,pct=Math.round(done/2);document.getElementById('prog').textContent=`${done} / 200 completed`;document.getElementById('bar').style.width=pct+'%';const hp=document.getElementById('heroProgress');if(hp)hp.textContent=pct+'% complete';const c=document.getElementById('continueBtn');if(c)c.textContent=done?'Continue · Set '+nextSet():'Start learning'}
document.addEventListener('click',e=>{const open=e.target.closest('[data-open-set]');if(open){openSet(open.dataset.openSet);return}if(e.target.closest('.backBtn')){renderMenu();return}const a=e.target.closest('.set');if(!a)return;if(e.target.classList.contains('mark'))mark(a);if(e.target.classList.contains('reset'))reset(a)});document.addEventListener('input',e=>{if(e.target.classList.contains('ans'))save(e.target.closest('.set'))});document.addEventListener('keydown',e=>{if(e.key!=='Enter'||!e.target.classList.contains('ans'))return;e.preventDefault();const a=e.target.closest('.set'),ins=[...a.querySelectorAll('.ans')],i=ins.indexOf(e.target);if(i<7)ins[i+1].focus();else mark(a)});document.getElementById('clearAll').onclick=()=>{if(confirm('Clear all saved answers and progress?')){for(let i=1;i<=200;i++){localStorage.removeItem('answers-'+i);localStorage.removeItem('done-'+i)}renderMenu()}};document.getElementById('continueBtn').onclick=()=>openSet(nextSet());renderMenu();