const NAMES=['Aina','Hafiz','Mei Ling','Kavin','Sara','Daniel','Nadia','Arun'];
const LEVELS=[['foundation','Foundation',1,15],['developing','Developing',16,30],['standard','Standard',31,70],['exam','Exam',71,100],['extra','Extra Practice',101,160],['challenge','Challenge',161,200]];
const DATA={pairs:()=>window.PAIRS||[],sets:()=>window.SETS||[]};
const STORE={get(k){try{return localStorage.getItem(k)}catch(e){return null}},set(k,v){try{localStorage.setItem(k,v)}catch(e){}},remove(k){try{localStorage.removeItem(k)}catch(e){}}};
const intros=[n=>`${n}'s class recently worked on a school activity. The task gave students a chance to practise English while completing a practical project.`,n=>`This term, ${n}'s class took part in a school project. Students worked in small groups and shared responsibility for different parts of the activity.`,n=>`The school recently organised an English activity, and ${n}'s class joined it. The students prepared their work over several lessons.`];
const mids=['During the preparation, the group checked its progress and made a few changes.','As the activity developed, students compared their ideas and improved the final version.','The class used the next few lessons to complete the preparation and check important details.'];
const outros=['At the end, the class discussed what had gone well and what could be improved next time.','After the session, the students reviewed the activity and shared what they had learned.','When the activity ended, the group packed the materials and talked about the experience.'];
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function sentence(pid,num,name,setNo,pos){const p=DATA.pairs()[pid];if(!p)return `<span class="error">(${num}) [question data unavailable]</span>`;const arr=p[5],t=arr[(setNo+pos)%arr.length];return t.replaceAll('{NAME}',name).replace('{M}',`<span class="error">(${num}) ${esc(p[0])}</span>`)}
function passage(set){const [n,title,ids]=set,name=NAMES[(n-1)%NAMES.length],start=n>=71?9:1,s=ids.map((pid,i)=>sentence(pid,start+i,name,n,i));return `<div class="passage"><p>${intros[n%3](name)} ${s.slice(0,3).join(' ')}</p><p>${mids[n%3]} ${s.slice(3,6).join(' ')}</p><p>${s.slice(6).join(' ')} ${outros[n%3]}</p></div>`}
function row(setNo,pid,i,start){return `<div class="answerRow"><label>${start+i}.</label><input class="ans" data-pid="${pid}" autocomplete="off" spellcheck="false"></div>`}
function card(set){const [n,title,ids]=set,start=n>=71?9:1;return `<div class="practiceTop"><a class="backBtn" href="./#learning-path">← Learning Path</a><span class="setCounter">Set ${n} / 200</span></div><article class="set" data-set="${n}"><div class="setHead"><h3>Set ${n} · ${esc(title)}</h3><small>8 marks</small></div><p class="instruction">${n>=71?'Questions 9–16. ':''}Read the text below and correct the eight underlined errors. Write the correct word or words in the spaces provided.</p>${passage(set)}<div class="answerGrid">${ids.map((p,i)=>row(n,p,i,start)).join('')}</div><div class="actions"><button class="btn mark">批改</button><button class="btn alt reset">重新作答</button></div><div class="result"></div><div class="corrections"></div></article>`}
function setButton(set){const [n,title]=set,done=STORE.get('done-'+n)==='1';return `<a class="setTile ${done?'done':''}" href="?set=${n}#practice"><span class="setNo">Set ${String(n).padStart(2,'0')}</span><span class="setTitle">${esc(title)}</span><span class="setStatus">${done?'✓ Completed':'Start →'}</span></a>`}
function renderMenu(){const sets=DATA.sets(),root=document.getElementById('practice');if(!sets.length){root.innerHTML='<section class="level"><h2>Question bank is loading...</h2><p>Please reload once.</p></section>';return}root.innerHTML=LEVELS.map(([id,label,a,b])=>{const ss=sets.filter(s=>s[0]>=a&&s[0]<=b);if(!ss.length)return '';return `<section class="level" id="${id}"><div class="levelTitle"><div><span class="pill">SETS ${a}–${b}</span><h2>${label}</h2></div></div><div class="setGrid">${ss.map(setButton).join('')}</div></section>`}).join('');updateProgress()}
function openSet(n){const sets=DATA.sets(),set=sets.find(s=>s[0]===Number(n)),root=document.getElementById('practice');if(!set){root.innerHTML=`<section class="level"><h2>Set ${n} is loading...</h2><p><a class="btn" href="?set=${n}&retry=1#practice">Reload Set ${n}</a></p></section>`;return}const missing=set[2].filter(id=>!DATA.pairs()[id]);if(missing.length){root.innerHTML=`<section class="level"><h2>Set ${n} question data is loading...</h2><p><a class="btn" href="?set=${n}&retry=1#practice">Reload Set ${n}</a></p></section>`;return}root.innerHTML=`<section class="level singlePractice">${card(set)}</section>`;restore();updateProgress()}
function norm(s){return s.trim().toLowerCase().replace(/[.,!?;:]+$/,'').replace(/\s+/g,' ')}
function mark(a){const ins=[...a.querySelectorAll('.ans')],blank=ins.find(x=>!x.value.trim()),r=a.querySelector('.result'),c=a.querySelector('.corrections');if(blank){r.textContent='请先完成8题再批改。';blank.focus();return}let score=0,wrong=[];ins.forEach((inp,i)=>{const p=DATA.pairs()[+inp.dataset.pid],ok=p&&norm(inp.value)===norm(p[1]);inp.classList.toggle('correct',ok);inp.classList.toggle('wrong',!ok);if(ok)score++;else wrong.push([i,p,inp.value])});r.innerHTML=score===8?'<span class="perfect">8/8 · 全部正确。这一套不需要订正。</span>':`${score}/8 · 请完成下面的订正。`;c.innerHTML=wrong.map(([i,p,v])=>`<div class="corr"><b>${i+1}. 你的答案：</b> ${esc(v)}<br><b>正确答案：</b> ${esc(p[1])}<br><b>为什么错：</b> ${esc(p[2])}<div class="cn"><b>订正规则：</b> ${esc(p[3])}<br><b>例子：</b> ${esc(p[4])}</div></div>`).join('');c.classList.toggle('show',wrong.length>0);save(a);if(score===8)STORE.set('done-'+a.dataset.set,'1');updateProgress()}
function save(a){STORE.set('answers-'+a.dataset.set,JSON.stringify([...a.querySelectorAll('.ans')].map(i=>i.value)))}
function restore(){document.querySelectorAll('.set').forEach(a=>{try{const v=JSON.parse(STORE.get('answers-'+a.dataset.set)||'[]');a.querySelectorAll('.ans').forEach((i,k)=>i.value=v[k]||'')}catch(e){}})}
function reset(a){a.querySelectorAll('.ans').forEach(i=>{i.value='';i.className='ans'});a.querySelector('.result').textContent='';a.querySelector('.corrections').innerHTML='';STORE.remove('answers-'+a.dataset.set);STORE.remove('done-'+a.dataset.set);updateProgress()}
function updateProgress(){const sets=DATA.sets(),done=sets.filter(s=>STORE.get('done-'+s[0])==='1').length,pct=Math.round(done/200*100);const p=document.getElementById('prog'),b=document.getElementById('bar'),h=document.getElementById('heroProgress');if(p)p.textContent=`${done} / 200 completed`;if(b)b.style.width=pct+'%';if(h)h.textContent=pct+'% complete'}
document.addEventListener('click',e=>{const a=e.target.closest('.set');if(!a)return;if(e.target.classList.contains('mark'))mark(a);if(e.target.classList.contains('reset'))reset(a)});document.addEventListener('input',e=>{if(e.target.classList.contains('ans'))save(e.target.closest('.set'))});document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.classList.contains('ans')){e.preventDefault();const a=e.target.closest('.set'),x=[...a.querySelectorAll('.ans')],i=x.indexOf(e.target);i<7?x[i+1].focus():mark(a)}});
const clear=document.getElementById('clearAll');if(clear)clear.onclick=()=>{if(confirm('Clear all saved answers and progress?')){for(let i=1;i<=200;i++){STORE.remove('answers-'+i);STORE.remove('done-'+i)}location.href='./'}};
const params=new URLSearchParams(location.search),wanted=Number(params.get('set')||0);wanted?openSet(wanted):renderMenu();